### PR TITLE
Bugfix/class not found jaxb

### LINKED ISSUE #80: New release to include latest coverage html assets
Assets of https://github.com/utPLSQL/utPLSQL-coverage-html got updated so we should create a new release of cli

### LINKED ISSUE #82: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter when Java 10 is installed
For cli is compiled to use Java 8 it will throw the following error when the default Java-version is 10 (or higher):

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at org.utplsql.api.reporter.Reporter.setAttributes(Reporter.java:80)
        at org.utplsql.api.reporter.Reporter.<init>(Reporter.java:29)
        at org.utplsql.api.reporter.DefaultReporter.<init>(DefaultReporter.java:15)
        at org.utplsql.api.reporter.ReporterFactory.createReporter(ReporterFactory.java:94)
        at org.utplsql.api.reporter.ReporterFactory.create(ReporterFactory.java:122)
        at oracle.jdbc.driver.Accessor.getORAData(Accessor.java:944)
        at oracle.jdbc.driver.OracleCallableStatement.getORAData(OracleCallableStatement.java:1864)
        at oracle.jdbc.driver.OracleCallableStatementWrapper.getORAData(OracleCallableStatementWrapper.java:789)
        at org.utplsql.api.reporter.Reporter.initDbReporter(Reporter.java:73)
        at org.utplsql.api.reporter.Reporter.init(Reporter.java:46)
        at org.utplsql.cli.ReporterManager.initReporters(ReporterManager.java:68)
        at org.utplsql.cli.RunCommand.run(RunCommand.java:158)
        at org.utplsql.cli.Cli.main(Cli.java:33)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more
```

This can be avoided if we pack java 1.8 rt.jar into lib folder.

### LINKED ISSUE #85: CLI opens too many connections
Since 3.1.0 cli opens way too many connections for the reporters. Seems like 10, no matter how many reporters are included.

### PR DESCRIPTION
**Pull request by pesse**
Fixes #82 
Fixes #80 
Fixes #85

### CODE REVIEW

File: src/main/java/org/utplsql/cli/RunCommand.java [hunk 1]
```diff
@@ -145,6 +144,9 @@ public int run() throws Exception {
         final ArrayList<String> finalIncludeObjectsList = includeObjectsList;
         final ArrayList<String> finalExcludeObjectsList = excludeObjectsList;
 
+        final ConnectionInfo ci = getConnectionInfo();
+        ci.setMaxConnections(getReporterManager().getNumberOfReporters()+1);
```
Comment (jgebal) [inline src/main/java/org/utplsql/cli/RunCommand.java]: Why +1?
